### ISSUE TITLE
Disponibilidade JAVA

### ISSUE THREAD

**Issue by M4Desenvolvimento** [DeveloperCielo/Webservice-1.5-java#2]
Olá boa tarde, já entrei contato via  email com o suporte da cielo (cieloecommerce@cielo.com.br) e fui instruido pelo Guilherme Furlan do suporte a entrar em contato  diretamente por aqui.

Sou responsável pelo desenvolvimento de plataformas ecommerce (Becommerce) da empresa Ecommet.

Atualmente temos integrado em nossas lojas os checkouts: Mercado Pago, PagSeguro e Bcash.

A alguns dias começamos a integração do "Checkout Cielo", e agora iriamos iniciar o Webservice1.5, porém ao entrar no repositório da Cielo para Java notamos que esta vazio, vocês conseguem corrigir esses arquivos?

**Comment by M4Desenvolvimento** [comment]
???

**Comment by netojoaobatista** [comment]
Olá @M4Desenvolvimento,

Até sexta-feira o código estará disponível novamente.

**Comment by M4Desenvolvimento** [comment]
Obrigado, estamos no aguardo.

**Comment by khrisnet** [comment]
Estamos no aguardo também.

**Comment by M4Desenvolvimento** [comment]
Acho que o feriadão deve ter atrapalhado, segunda teremos a API disponível??

**Comment by khrisnet** [comment]
Bom dia,

Possui uma nova previsão para que seja disponibilizado @netojoaobatista?

**Comment by M4Desenvolvimento** [comment]
@netojoaobatista consegue passar uma data real para a disponibilidade desta API ?

**Comment by M4Desenvolvimento** [comment]
Pessoal estamos com clientes dependendo dessa implementação. Alguma previsão?

**Comment by yagotlima** [comment]
Olá. Os códigos que estariam disponiveis aqui seriam muito diferentes daqueles que eram disponibilizados na aplicação de exemplo da [documentação antiga](https://www.cielo.com.br/portal/kit-e-commerce-cielo.html%20manual%202.0)?

**Comment by eduardodaluz** [comment]
Também estou no aguardo

**Comment by jlccaires** [comment]
Cadê o código? Devo procurar outra solução?

**Comment by julianoeustaquio** [comment]
@netojoaobatista existe uma previsão de quando será disponibilizado?

Grato
